version: 2.1
orbs:
  python: circleci/python@1.4.0

jobs:
  build:
    executor: python/default
    steps:
      - checkout
      - python/dist

  test:
    executor: python/default
    steps:
      - checkout
      - run:
          name: Install dev dependencies
          command: make install-dev
      - run:
          name: Run pytest
          command: pytest -x -v --disable-pytest-warnings

  lint:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run linters
          command: make local-lint


workflows:
  build_test_link:
    jobs:
      - build
      - test
      - lint
